FROM golang:alpine
MAINTAINER "Double Wen <wyatthaha@126.com>"

RUN rm -rf /var/cache/apk/* && \
    apk update && \
    apk add git build-base && \
    mkdir -p "$GOPATH/src/github.com/wyatt88/k8swatch"

ADD . "$GOPATH/src/github.com/wyatt88/k8swatch"

RUN cd "$GOPATH/src/github.com/wyatt88/k8swatch" && \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a --installsuffix cgo --ldflags="-s" -o /bin/k8swatch

ENTRYPOINT ["/bin/k8swatch"]
